services:
  - type: web
    name: tcup-dash
    runtime: python
    pythonVersion: 3.10.14         # ← this is the crucial line
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --timeout 120
