services:
  - type: web
    name: tcup-dash
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
